version: '3'

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "8000:80"
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www/html
            - ./logs:/var/log/nginx
        networks:
            - project
        depends_on:
            - php
        restart: unless-stopped
    php:
        image: wordpress:php7.4-fpm
        container_name: site-fpm
        env_file: .env
        depends_on: 
            - mysql
        volumes:
            - ./www:/var/www/html
        networks:
            - project
        restart: unless-stopped
    mysql:
        image: mariadb
        container_name: mysql
        volumes:
            - ./mysql:/var/lib/mysql
        command: "--init-file /var/lib/mysql/mysql_init.sql"
        environment:
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - project
    pma:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        restart: unless-stopped
        networks:
            - project
        ports:
            - 8183:80
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: secret

networks:
    project:
        driver: bridge
